### ISSUE TITLE
Error on new Tadingview update 30/oct

### ISSUE THREAD

**Issue by tresmastres** [alleyway/add-tradingview-alerts-tool#1]
Hello

I tray to use today after the Tradingview update

https://www.tradingview.com/blog/en/new-stable-version-of-charting-library-and-trading-terminal-21319/

And stucks after opens the Chromium browser and gives this error.

TimeoutError: waiting for XPath `//*[@id="header-toolbar-symbol-search"]/div/input` failed: timeout 30000ms exceeded
    at new WaitTask (C:\Users\tresmastres\add-tradingview-alerts-tool\node_modules\puppeteer\lib\cjs\puppeteer\common\DOMWorld.js:411:34)
    at DOMWorld.waitForXPath (C:\Users\tresmastres\add-tradingview-alerts-tool\node_modules\puppeteer\lib\cjs\puppeteer\common\DOMWorld.js:336:26)
    at Frame.waitForXPath (C:\Users\tresmastres\add-tradingview-alerts-tool\node_modules\puppeteer\lib\cjs\puppeteer\common\FrameManager.js:866:51)
    at Page.waitForXPath (C:\Users\tresmastres\add-tradingview-alerts-tool\node_modules\puppeteer\lib\cjs\puppeteer\common\Page.js:1325:33)
    at C:\Users\tresmastres\add-tradingview-alerts-tool\src\add-tradingview-alerts.ts:31:16
    at step (C:\Users\tresmastres\add-tradingview-alerts-tool\lib\add-tradingview-alerts.js:33:23)
    at Object.next (C:\Users\tresmastres\add-tradingview-alerts-tool\lib\add-tradingview-alerts.js:14:53)
    at C:\Users\tresmastres\add-tradingview-alerts-tool\lib\add-tradingview-alerts.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\tresmastres\add-tradingview-alerts-tool\lib\add-tradingview-alerts.js:4:12)

**Comment by mlake** [comment]
thanks for reporting.

Made a minor tweak that should fix this in 1.0.2
