### ISSUE TITLE
problem with message part in config.yml

### ISSUE THREAD

**Issue by stoofman** [alleyway/add-tradingview-alerts-tool#10]
Hello, I am having an issue when I make changes to the message part in the config.yml.
Can I add custom text ? When I try to use my own message format, and I run the tool, it gives this error and quits ....
I would like to add my own message in a format like this :

message: >
    {
         "key": "H1aJKI67711",
         "msg": "Long signal at `{{close}}`",
         "pair": "{{quote}}_{{base}}"
    }

when I add this and I run the tool I get this output :

Using config file:  config.yml
Press Ctrl-C to stop this script
<ref *1> YAMLSyntaxError: All collection items must start at the same column
    at Collection.parse (/home/user/add-tradingview-alerts-tool/node_modules/yaml/dist/parse-cst.js:331:24)
    at /home/user/add-tradingview-alerts-tool/node_modules/yaml/dist/parse-cst.js:1605:29
    at Document.parseContents (/home/user/add-tradingview-alerts-tool/node_modules/yaml/dist/parse-cst.js:622:26)
    at Document.parse (/home/user/add-tradingview-alerts-tool/node_modules/yaml/dist/parse-cst.js:685:19)
    at Object.parse (/home/user/add-tradingview-alerts-tool/node_modules/yaml/dist/parse-cst.js:1723:18)
    at parseDocument (/home/user/add-tradingview-alerts-tool/node_modules/yaml/dist/index.js:43:24)
    at Object.parse (/home/user/add-tradingview-alerts-tool/node_modules/yaml/dist/index.js:55:15)
    at /home/user/add-tradingview-alerts-tool/src/add-tradingview-alerts.ts:207:25
    at step (/home/user/add-tradingview-alerts-tool/lib/add-tradingview-alerts.js:33:23)
    at Object.next (/home/user/add-tradingview-alerts-tool/lib/add-tradingview-alerts.js:14:53) {
  source: Collection {
    error: [Circular *1],
    range: Range { start: 0, end: 894 },
    valueRange: Range { start: 0, end: 893 },
    props: [],
    type: 'MAP',
    value: null,
    items: [
      [PlainValue],
      [CollectionItem],
      [PlainValue],
      [CollectionItem],
      [PlainValue],
      [CollectionItem],
      [PlainValue],
      [CollectionItem],
      [PlainValue],
      [CollectionItem],
      [PlainValue]
    ],
    resolved: YAMLMap {
      items: [Array],
      schema: undefined,
      range: [Array],
      type: 'MAP'
    }
  }
}

**Comment by mlake** [comment]
The format of the config file is YAML

White space and tabs matter in this format, you probably need some tabs in there or something

**Comment by stoofman** [comment]
thanks, this helped me solving my issue. I removed some white spaces and used tabs instead.
thanks again , love the project !
