### ISSUE TITLE
SyntaxError: Unexpected reserved word

### ISSUE THREAD

**Issue by yuis-ice** [alleyway/add-tradingview-alerts-tool#113]
```
> C:\ProgramData\nvm\v14.15.0\npx.cmd @alleyway/create-tradingview-alerts-home
npx: 5個のパッケージを6.489秒でインストールしました。
(node:51380) ExperimentalWarning: The ESM module loader is experimental.
file:///C:/Users/user/AppData/Roaming/npm-cache/_npx/51380/node_modules/@alleyway/create-tradingview-alerts-home/dist/index.js:9
const manifest = JSON.parse(await readFile(new URL('./manifest.json', import.meta.url)));
                            ^^^^^

SyntaxError: Unexpected reserved word
    at Loader.moduleStrategy (internal/modules/esm/translators.js:81:18)  
    at async link (internal/modules/esm/module_job.js:37:21)
```

Environment: 

Windows 10 latest build
node 14.15.0
npx 6.14.8
npm 6.14.8
non admin cmd / admin powershell

**Comment by mlake** [comment]
maybe the node version needs to be updated? I've got it working fine on windows 10

![image](https://user-images.githubusercontent.com/764071/152422720-8bd0c220-e610-4464-ac9b-f342f2094e0d.png)

**Comment by yuis-ice** [comment]
It was a nvm misconfiguration in my environment. Your tool works nice now. Thanks for your kind help.
