### ISSUE TITLE
Error installing

### ISSUE THREAD

**Issue by DungPT10** [alleyway/add-tradingview-alerts-tool#22]
Hi Sir,
Can you help me check and resolve this Error .

![image](https://user-images.githubusercontent.com/69800731/111563867-5939c080-87cb-11eb-9d9c-57cf60262cb8.png)

**Comment by DominikBritz** [comment]
I get the same error. Running it on Windows.

```
import { TimeoutError } from "puppeteer";
         ^^^^^^^^^^^^
SyntaxError: Named export 'TimeoutError' not found. The requested module 'puppeteer' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from 'puppeteer';
const { TimeoutError } = pkg;

    at ModuleJob._instantiate (node:internal/modules/esm/module_job:105:21)
    at ModuleJob.run (node:internal/modules/esm/module_job:151:5)
    at Loader.import (node:internal/modules/esm/loader:166:24)
    at Object.loadESM (node:internal/process/esm_loader:68:5)
```

Versions:

```
PS C:\tv-alerts> npm version
{
  '@alleyway/add-tradingview-alerts-tool': '1.6.3',
  npm: '7.6.0',
  node: '15.11.0',
  v8: '8.6.395.17-node.27',
  uv: '1.41.0',
  zlib: '1.2.11',
  brotli: '1.0.9',
  ares: '1.17.1',
  modules: '88',
  nghttp2: '1.42.0',
  napi: '7',
  llhttp: '2.1.3',
  openssl: '1.1.1j',
  cldr: '38.1',
  icu: '68.2',
  tz: '2020d',
  unicode: '13.0'
}
```

**Comment by mlake** [comment]
Either you need to update your version of node to 14+ or you haven’t run “npm install” per installation instructions

**Comment by DominikBritz** [comment]
Node is on version `15.11.0`, see above. I've run `npm install` as well.

**Comment by mlake** [comment]
oops - looks like I may have broken it.

I just updated the project with a fix

**Comment by DungPT10** [comment]
still have Errors after updated new version !
Can you help me , Sir ?
![image](https://user-images.githubusercontent.com/69800731/111654394-4ced4c00-883b-11eb-8a5f-db803593efbb.png)

**Comment by DominikBritz** [comment]
I also facing errors. I switched to Ubuntu. Installation worked fine, but I'm unable to pull pairs or create an alert. Below the debug log of the command `npm run fetch:binance btc`

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'fetch:binance', 'btc' ]
2 info using npm@6.14.8
3 info using node@v12.18.2
4 verbose run-script [ 'prefetch:binance', 'fetch:binance', 'postfetch:binance' ]
5 info lifecycle @alleyway/add-tradingview-alerts-tool@1.6.7~prefetch:binance: @alleyway/add-tradingview-alerts-tool@1.6.7
6 info lifecycle @alleyway/add-tradingview-alerts-tool@1.6.7~fetch:binance: @alleyway/add-tradingview-alerts-tool@1.6.7
7 verbose lifecycle @alleyway/add-tradingview-alerts-tool@1.6.7~fetch:binance: unsafe-perm in lifecycle true
8 verbose lifecycle @alleyway/add-tradingview-alerts-tool@1.6.7~fetch:binance: PATH: /usr/share/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/dominik/Desktop/add-tradingview-alerts-tool-master/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin
9 verbose lifecycle @alleyway/add-tradingview-alerts-tool@1.6.7~fetch:binance: CWD: /home/dominik/Desktop/add-tradingview-alerts-tool-master
10 silly lifecycle @alleyway/add-tradingview-alerts-tool@1.6.7~fetch:binance: Args: [
10 silly lifecycle   '-c',
10 silly lifecycle   'npx tsc && cross-env EXCHANGE=BINANCE node -r source-map-support/register lib/fetch-pairs.js "btc"'
10 silly lifecycle ]
11 silly lifecycle @alleyway/add-tradingview-alerts-tool@1.6.7~fetch:binance: Returned: code: 1  signal: null
12 info lifecycle @alleyway/add-tradingview-alerts-tool@1.6.7~fetch:binance: Failed to exec fetch:binance script
13 verbose stack Error: @alleyway/add-tradingview-alerts-tool@1.6.7 fetch:binance: `npx tsc && cross-env EXCHANGE=BINANCE node -r source-map-support/register lib/fetch-pairs.js "btc"`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/share/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:315:20)
13 verbose stack     at ChildProcess.<anonymous> (/usr/share/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:315:20)
13 verbose stack     at maybeClose (internal/child_process.js:1021:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
14 verbose pkgid @alleyway/add-tradingview-alerts-tool@1.6.7
15 verbose cwd /home/dominik/Desktop/add-tradingview-alerts-tool-master
16 verbose Linux 5.8.0-44-generic
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "run" "fetch:binance" "btc"
18 verbose node v12.18.2
19 verbose npm  v6.14.8
20 error code ELIFECYCLE
21 error errno 1
22 error @alleyway/add-tradingview-alerts-tool@1.6.7 fetch:binance: `npx tsc && cross-env EXCHANGE=BINANCE node -r source-map-support/register lib/fetch-pairs.js "btc"`
22 error Exit status 1
23 error Failed at the @alleyway/add-tradingview-alerts-tool@1.6.7 fetch:binance script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by mlake** [comment]
Geez - I’m having a rough time getting it right today…try now

**Comment by DominikBritz** [comment]
It's working now with Ubuntu and NodeJS 14. Thanks so much!
