### ISSUE TITLE
csv.format is not a function

### ISSUE THREAD

**Issue by nomad5am** [alleyway/add-tradingview-alerts-tool#26]
Great tool buddy! One issue with fetching the pairs:

**In config is set:**
  input: ftx_perp_pairs.csv

**Error:**
```
> @alleyway/add-tradingview-alerts-tool@1.6.9 fetch:ftx
> npx tsc && npx cross-env EXCHANGE=FTX node -r source-map-support/register dist/fetch-pairs.js "perp"

(node:7361) ExperimentalWarning: The ESM module loader is experimental.
TypeError: csv.format is not a function
    at file:///Users/sam/dev/add-tradingview-alerts-tool/src/fetch-pairs.ts:27:27
    at Generator.next (<anonymous>)
    at fulfilled (file:///Users/sam/dev/add-tradingview-alerts-tool/dist/fetch-pairs.js:4:58)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

**Comment by mlake** [comment]
looks like you need to update your node version buddy
