### ISSUE TITLE
Error: npm run fetch:binance usdt

### ISSUE THREAD

**Issue by Ajki-GH** [alleyway/add-tradingview-alerts-tool#27]
Any idea what could be wrong 

```
SyntaxError: Unexpected identifier
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @alleyway/add-tradingview-alerts-tool@1.6.9 fetch:binance: `npx tsc && npx cross-env EXCHANGE=BINANCE node -r source-map-support/register dist/fetch-pairs.js "usdt"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @alleyway/add-tradingview-alerts-tool@1.6.9 fetch:binance script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by mlake** [comment]
update your node version to 12 or greater
