### ISSUE TITLE
XPath Generator not working

### ISSUE THREAD

**Issue by GogeiD** [alleyway/add-tradingview-alerts-tool#35]
Hi there! First, thanks a lot for maintaining this project. It's really an underserved feature. 

Just to let you know that, at least for me, the XPath Generator download link is not working, and the tool is not running without it. I have tried some alternatives, to no avail, or.....

The problem may be different: I am using the tool to add strategy alerts.  With this option a bunch of options disappear (once per bar, and some other tertiary fields) I am eliminating those from the config file, since the tool won't find any. Am I doing something wrong? Apart from being unable to install the XPath Generator, I am following the instructions (bear with me, I am a nurse with zero coding experience whatsoever).

Here is the error log:

13 verbose stack Error: @alleyway/add-tradingview-alerts-tool@1.6.10 add-alerts: `npx tsc && npx cross-env node --es-module-specifier-resolution=node -r source-map-support/register dist/add-alerts.js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:315:20)
13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:315:20)
13 verbose stack     at maybeClose (internal/child_process.js:1048:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
14 verbose pkgid @alleyway/add-tradingview-alerts-tool@1.6.10
15 verbose cwd C:\Users\Diego Garcia\add-tradingview-alerts-tool
16 verbose Windows_NT 10.0.18363
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "add-alerts"
18 verbose node v14.16.0
19 verbose npm  v6.14.11
20 error code ELIFECYCLE
21 error errno 1
22 error @alleyway/add-tradingview-alerts-tool@1.6.10 add-alerts: `npx tsc && npx cross-env node --es-module-specifier-resolution=node -r source-map-support/register dist/add-alerts.js`
22 error Exit status 1
23 error Failed at the @alleyway/add-tradingview-alerts-tool@1.6.10 add-alerts script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

Thanks a lot for your guidance! I really appreciate it.

Diego

**Comment by GogeiD** [comment]
Never mind, it works without the XPath generator. No need to delete the actual line from the config file, just leave it blank.

Working just fine so far. Thanks again for your effort in putting this together.
