### ISSUE TITLE
Issue with tertiaryRight condition

### ISSUE THREAD

**Issue by zerocomte** [alleyway/add-tradingview-alerts-tool#51]
Hello guy,

I try this:
alert:
  condition:
    primaryLeft: MA Emperor insiliconot
    primaryRight: P
    secondary: Croisement vers le haut
    tertiaryLeft: MA Emperor insiliconot
    tertiaryRight: MA 2
    quaternaryLeft: 
    quaternaryRight: 

Step Primary is ok
Step Secondary is ok
Step tertiaryLeft is ok
Step tertiaryRight is ko

This last one can't be change, it could not open the dropdown menu.

Error:
ERROR  waiting for XPath (//div[contains(@class, 'tv-alert-dialog__group-item--right ')]/div[contains(@class, 'js-number-input')]/input)[1] failed: timeout 3000ms exceeded

I am using the version 1.8.0.

Kind regards,
Thomas

**Comment by ramnite** [comment]
After being able to upgrade to ATAT latest version (https://github.com/alleyway/add-tradingview-alerts-tool/issues/54), I am experiencing the same issue as @zerocomte with tertiaryRigh condition.

In my case, my alert is very simple, nothing fancy. Just a MACD Line crossing up the MACD Signal.

The alert creation process seem to work fine until it reaches the tertiaryRigh condition ("Signal"), which triggers the following error:
 ERROR  waiting for XPath (//div[contains(@class, 'tv-alert-dialog__group-item--right ')]/div[contains(@class, 'js-number-input')]/input)[1] failed: timeout 3000ms exceeded

```
  at new WaitTask (/usr/local/lib/node_modules/@alleyway/add-tradingview-alerts-tool/node_modules/puppeteer/src/common/DOMWorld.ts:780:28)
  at DOMWorld.waitForXPath (/usr/local/lib/node_modules/@alleyway/add-tradingview-alerts-tool/node_modules/puppeteer/src/common/DOMWorld.ts:675:22)
  at Frame.waitForXPath (/usr/local/lib/node_modules/@alleyway/add-tradingview-alerts-tool/node_modules/puppeteer/src/common/FrameManager.ts:1193:47)
  at Page.waitForXPath (/usr/local/lib/node_modules/@alleyway/add-tradingview-alerts-tool/node_modules/puppeteer/src/common/Page.ts:2111:29)
  at fetchFirstXPath (/usr/local/lib/node_modules/@alleyway/add-tradingview-alerts-tool/src/service/tv-page-actions.ts:15:20)
  at performActualEntry (/usr/local/lib/node_modules/@alleyway/add-tradingview-alerts-tool/src/service/tv-page-actions.ts:208:50)
  at configureSingleAlertSettings (/usr/local/lib/node_modules/@alleyway/add-tradingview-alerts-tool/src/service/tv-page-actions.ts:238:5)
  at addAlert (/usr/local/lib/node_modules/@alleyway/add-tradingview-alerts-tool/src/service/tv-page-actions.ts:331:5)
  at addAlertsMain (/usr/local/lib/node_modules/@alleyway/add-tradingview-alerts-tool/src/add-alerts.ts:209:9)
  at Command.<anonymous> (/usr/local/lib/node_modules/@alleyway/add-tradingview-alerts-tool/src/cli.ts:67:13)
```

**Comment by mlake** [comment]
Could each of you try installing a beta release and confirm the fix?
```
npm install @alleyway/add-tradingview-alerts-tool@beta
```

@ramnite looks like you have a permissions issue from all the sudo commands...
You could try the following:
```
sudo chown -R $(whoami) .
```
To avoid permissions hell, you might want to think about installing NVM:
https://github.com/nvm-sh/nvm

**Comment by zerocomte** [comment]
![image](https://user-images.githubusercontent.com/17379918/117658781-72436a00-b19b-11eb-8223-3009bebee307.png)


I installed. I tried. But same resultat. It can't found the dropdown list.

![failed](https://user-images.githubusercontent.com/17379918/117659043-bdf61380-b19b-11eb-8ff9-9fa3a6942f70.PNG)

**Comment by mlake** [comment]
@zerocomte I should have mentioned that you should run that command in the same directory your config files are located..

lools like you're doing everything in "C:/Users/thomas/Documents/TV/" so that's where you should run the command

the ATAT Version should end being **1.8.4-beta.0**

**Comment by zerocomte** [comment]
Oh sorry, my mistake!

**Comment by zerocomte** [comment]
Now, with update into the good repository, That is working great:

![image](https://user-images.githubusercontent.com/17379918/117660987-16c6ab80-b19e-11eb-8977-a2aa527a4206.png)

**Comment by mlake** [comment]
ça roule...i will close this issue then! Happy alerting!

**Comment by zerocomte** [comment]
Merci!

Have a nice day!

**Comment by ramnite** [comment]
Thanks for the tip about permissions. I will look into it later, unless you think that it is related with my current issue.

Unlike zercomte, the issue persists for me. As you can see, I have installed the beta version but still receiving the same error:

![Screen Shot 2021-05-10 at 14 56 17](https://user-images.githubusercontent.com/80322035/117662627-0d3e4300-b1a0-11eb-9688-d910e9c616dd.png)
