### ISSUE TITLE
tertiaryRight fails to find input xpath

### ISSUE THREAD

**Issue by lucasnoah** [alleyway/add-tradingview-alerts-tool#7]
I kept getting input errors when trying to use the tertiary right number input with a Greater than secondary input. Changing the xpath selector for that input seemed to do the trick.  Not sure if this will break a bunch of stuff, so I will skip the PR. 

ERROR EXAMPLE
```
TimeoutError: waiting for XPath `//div[@class='tv-control-number-input tv-control-number-input--size_small js-number-input__wrap js-period-input-wrap']/input[@class='tv-alert-dialog__number-input tv-control-input tv-control-input--size_small js-number-input' and 1]` failed: timeout 1000ms exceeded
    at new WaitTask (/Users/lucasn/localdev/add-tradingview-alerts-tool/node_modules/puppeteer/lib/cjs/puppeteer/common/DOMWorld.js:505:34)
    at DOMWorld.waitForXPath (/Users/lucasn/localdev/add-tradingview-alerts-tool/node_modules/puppeteer/lib/cjs/puppeteer/common/DOMWorld.js:441:26)
    at Frame.waitForXPath (/Users/lucasn/localdev/add-tradingview-alerts-tool/node_modules/puppeteer/lib/cjs/puppeteer/common/FrameManager.js:866:51)
    at Page.waitForXPath (/Users/lucasn/localdev/add-tradingview-alerts-tool/node_modules/puppeteer/lib/cjs/puppeteer/common/Page.js:1288:33)
    at /Users/lucasn/localdev/add-tradingview-alerts-tool/src/add-tradingview-alerts.ts:33:16
    at step (/Users/lucasn/localdev/add-tradingview-alerts-tool/lib/add-tradingview-alerts.js:33:23)
    at Object.next (/Users/lucasn/localdev/add-tradingview-alerts-tool/lib/add-tradingview-alerts.js:14:53)
    at /Users/lucasn/localdev/add-tradingview-alerts-tool/lib/add-tradingview-alerts.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/lucasn/localdev/add-tradingview-alerts-tool/lib/add-tradingview-alerts.js:4:12)

```

FIX
```
const inputXpathQueries = {
    tertiaryLeft: "//div[@class='tv-control-number-input tv-control-number-input--size_small js-number-input__wrap js-move-value-input-wrap']/input[@class='tv-alert-dialog__number-input tv-control-input tv-control-input--size_small js-number-input' and 1]",
    tertiaryRight: "//*[@id=\"overlap-manager-root\"]/div/div/div[2]/div[1]/div/div/p/form/fieldset/div[3]/span/div[2]/div"
}
```

Cheers!

**Comment by mlake** [comment]
Hey Lucas - I was able to reproduce and fixed it with a more robust xpath query. Thanks for reporting this!
Please let me know if you run into anything else.
-Michael
