### ISSUE TITLE
How fast is it recommended to use `--delay` ? Unable to find Xpath target for primaryLeft/secondary which doesn't have inputs, so won't even try

### ISSUE THREAD

**Issue by avatar-lavventura** [alleyway/add-tradingview-alerts-tool#70]
> `Moving too fast for your connection speed? Try adjusting the delay option (default is 1000)`

How fast is recommended to use `--delay`? Can we use `--delay 100`?

Can we do `--delay 1`? When I try that fast the given alert name is not found and the code stops. If there is an error can we apply an exception to re-try again and continue the operation?

Even for `--delay 1100` I am getting following error, and I have to restart adding the alerts:

```
 ERROR  Unable to find Xpath target for primaryLeft/secondary which doesn't have inputs, so won't even try                                                                                                                                18:28:16

  at performActualEntry (node_modules/@alleyway/add-tradingview-alerts-tool/src/service/tv-page-actions.ts:228:32)
  at configureSingleAlertSettings (node_modules/@alleyway/add-tradingview-alerts-tool/src/service/tv-page-actions.ts:238:5)
  at addAlert (node_modules/@alleyway/add-tradingview-alerts-tool/src/service/tv-page-actions.ts:360:5)
  at addAlertsMain (node_modules/@alleyway/add-tradingview-alerts-tool/dist/add-alerts.js:175:9)
  at Command.<anonymous> (node_modules/@alleyway/add-tradingview-alerts-tool/src/cli.ts:77:13)
```

**Comment by mlake** [comment]
default is 1000, so I would experiment with 2000 to see if that works, if not, try 3000..if that works, then try 2500..and so on..

**Comment by avatar-lavventura** [comment]
@mlake I was able to make it work with `--delay 1500`.

Just a minor note. I have called ` await sleep(20000);` right before `if (accessDenied)` check in the `add-alerts.js` file. That gives me time to remove alerts and update the strategy I am using.


```
function sleep(ms) {
  return new Promise((resolve) => {
    setTimeout(resolve, ms);
  });
}
```
