### ISSUE TITLE
val.replace is not a function

### ISSUE THREAD

**Issue by backslash-f** [alleyway/add-tradingview-alerts-tool#88]
Howdy! Nice tool!

Unfortunately I'm facing the following issue after running `$ ./atat add-alerts --loglevel 5`:

```
ℹ ATAT Version: 1.9.1 | Node Version: v16.9.1                                                                                                                00:54:50
ℹ Current log level: 5 (you can specify '--loglevel 5' for maximum debugging)                                                                                00:54:50
ℹ Base delay: 1000 (you can specify '--delay 1000' (or env variable BASE_DELAY) to increase/decrease speed)                                                  00:54:50
ℹ Using config file:  config.yml                                                                                                                             00:54:50
ℹ Press Ctrl-C to stop this script                                                                                                                           00:54:50
› Reading input file: binance_pairs.csv                                                                                                                      00:54:50
› ...waiting 5000ms = 5 x 1000  let page load and see if access is denied                                                                                    00:54:52
› ...waiting 3000ms = 3 x 1000  wait a little longer for page to load                                                                                        00:54:57
› minimizing footer chart panel                                                                                                                              00:55:00
› ...selector: //div[@id='footer-chart-panel']//button[@data-name='toggle-visibility-button' and @data-active='false']                                       00:55:00
› no minimize button found, footer chart panel must be hidden already                                                                                        00:55:05
› set interval: 4h                                                                                                                                           00:55:05
› ...waiting 500ms = 0.5 x 1000  after pressing interval shortcut key                                                                                        00:55:05
› ...waiting 3000ms = 3 x 1000  after changing the interval                                                                                                  00:55:06
ℹ Adding symbol: BINANCE:ADAEUR  ( ADA priced in EUR )                                                                                                       00:55:09
› ...waiting 2000ms = 2 x 1000  let things settle from processing last alert                                                                                 00:55:09
› ...selector: //div[@id="header-toolbar-symbol-search"]                                                                                                     00:55:11
› ...waiting 1000ms = 1 x 1000                                                                                                                               00:55:11
› ...waiting 300ms = 0.3 x 1000                                                                                                                              00:55:12
› ...waiting 2000ms = 2 x 1000  after navigating to ticker                                                                                                   00:55:12

 ERROR  val.replace is not a function                                                                                                                        00:55:14

  at makeReplacements (node_modules/@alleyway/add-tradingview-alerts-tool/src/add-alerts.ts:191:31)
  at addAlertsMain (node_modules/@alleyway/add-tradingview-alerts-tool/src/add-alerts.ts:216:32)
  at Command.<anonymous> (node_modules/@alleyway/add-tradingview-alerts-tool/src/cli.ts:77:13)
```

My `binance_pairs.csv`:

```
symbol,base,quote,name
BINANCE:ADAEUR,ADA,EUR,
```

My `config.yml`:

```
files:
  input: binance_pairs.csv
  exclude: blacklist.csv
tradingview:
  chartUrl: https://www.tradingview.com/chart/xYYRDSPL/
  interval: 4h
alert:
  condition:
    primaryLeft: RSI
    primaryRight:
    secondary: Crossing
    tertiaryLeft: Value
    tertiaryRight: 30.00
  option: Once Per Bar
  actions:
    notifyOnApp: true
    showPopup: true
    sendEmail: false
  name: "RSI 30 (4h) for {{symbol}}"
```

Any ideas on what's going on?
Thanks!

**Comment by mlake** [comment]
Should be working in the most recent release.

From your ``tradingview-alerts-home`` directory, run the following:

```bash
npm install @alleyway/add-tradingview-alerts-tool@latest
```
